"$schema" = "https://yazi-rs.github.io/schemas/theme.json"

[mgr]

cwd = { fg = "cyan" }

hovered = { reversed = true }
preview_hovered = {}

find_keyword = { fg = "yellow", bold = true }
find_position = { fg = "yellow", reversed = true }

marker_copied = { fg = "yellow", bg = "reset" }
marker_cut = { fg = "red", bg = "reset" }
marker_marked = { fg = "lightmagenta", bg = "reset" }
marker_selected = { fg = "magenta", bg = "reset" }

count_copied = { fg = "black", bg = "yellow" }
count_cut = { fg = "black", bg = "red" }
count_selected = { fg = "black", bg = "magenta" }

border_symbol = " "
border_style = { fg = "black" }

[tabs]

active = { fg = "gray", bg = "reset" }
inactive = { fg = "darkgray", bg = "reset" }

sep_inner = { open = "", close = "" }
sep_outer = { open = "", close = "" }

[mode]

normal_main = { fg = "black", bg = "gray" }
select_main = { fg = "black", bg = "lightmagenta" }
unset_main = { fg = "black", bg = "red" }

[status]

overall = { fg = "gray" }

sep_left = { open = "", close = "" }
sep_right = { open = "", close = "" }

progress_label = { reverse = true }
progress_normal = { fg = "blue", bg = "reset" }
progress_error = { fg = "red", bg = "reset" }

perm_type = { fg = "cyan", bg = "reset" } # used only for dirs
perm_read = { fg = "gray", bg = "reset" }
perm_write = { fg = "gray", bg = "reset" }
perm_exec = { fg = "gray", bg = "reset" }
perm_sep = { fg = "darkgray", bg = "reset" }

[pick]

border = { fg = "darkgray" }
active = { fg = "reset" }
inactive = { fg = "gray" }

[input]

border = { fg = "darkgray" }
title = { fg = "darkgray" }
value = { fg = "reset" }
selected = { bg = "darkgray" }

[confirm]

border = { fg = "darkgray" }
title = { fg = "darkgray" }
content = { fg = "gray" }
list = { fg = "gray" }
btn_yes = { fg = "darkgray" }
btn_no = { fg = "darkgray" }
btn_labels = ["Yes", "No"]

[spot]

border = { fg = "darkgray" }
title = { fg = "darkgray" }
tbl_col = { fg = "reset" }
tbl_cell = { fg = "reset", reversed = true }

[cmp]

border = { fg = "darkgray" }
active = { fg = "reset" }
inactive = { fg = "gray" }

icon_file = "󰈤"
icon_folder = "󰝰"
icon_command = ""

[tasks]

border = { fg = "darkgray" }
title = { fg = "darkgray" }
hovered = { fg = "reset", bg = "darkgray" }

[which]

cols = 2
mask = { bg = "reset" }
cand = { fg = "magenta" }
rest = { fg = "darkgray" }
desc = { fg = "gray" }
separator = " "

[help]

on = { fg = "magenta", bg = "reset" }
run = { fg = "darkgray" }
desc = { fg = "gray" }
hovered = { bold = true }
footer = { fg = "gray", bg = "reset" }

[notify]

title_info = { fg = "green" }
title_warn = { fg = "yellow" }
title_error = { fg = "red" }

icon_info = ""
icon_warn = ""
icon_error = ""

[filetype]

rules = [
  { url = "*", is = "exec", fg = "green" },

  { url = "*.{AppImage,flatpak}", fg = "green" },

  { url = "*.{bat,cmd,exe,ps1}", fg = "green" },

  { url = "*.{deb,rpm}", fg = "yellow" },

  { url = "*.{7z,gz,rar,tar,zip}", fg = "yellow" },

  { url = "*.{cow,fsa,iso,mrimg,mrimgx,wim}", fg = "magenta" },

  { mime = "{audio,image,video}/*", fg = "magenta" },

  { url = "*.{classpath,factorypath,project}", fg = "gray" },
  { url = "*.dockerignore", fg = "gray" },
  { url = "*.editorconfig", fg = "gray" },
  { url = "*.{env,eslintignore,eslintrc,eslintrc.js,eslintrc.json,npmrc,nvmrc,yarnrc}", fg = "gray" },
  { url = "*.{git,gitattributes,gitignore,gitkeep,gitmodules}", fg = "gray" },
  { url = "*.lock", fg = "gray" },
  { url = "*.{luacheckrc,luarc.json,stylua.toml}", fg = "gray" },
  { url = "*.{prettierignore,prettierrc}", fg = "gray" },
  { url = "*.pylintrc", fg = "gray" },
  { url = "*.taplo.toml", fg = "gray" },
  { url = "*.vscodeignore", fg = "gray" },

  { url = "*.{backup,bak,log,off,old,orig,original,part,swp,tmp}", fg = "darkgray" },

  { url = "*.{cache,config,local}/", fg = "gray" },

  { url = "*.{cert,pki,ssh}/", fg = "gray" },

  { url = "*.{android,angular,ansible,azure-pipelines,devcontainer,dotnet,gemini,git,github,husky,idea,java,jupyter,m2,settings,swt,venv,vscode,yarn}/", fg = "gray" },

  { url = "*__pycache__/", fg = "gray" },
  { url = "*dist/", fg = "gray" },
  { url = "*node_modules/", fg = "gray" },

  { url = "*.obsidian/", fg = "gray" },
  { url = "*.steam/", fg = "gray" },

  # windows

  { url = "*$winre_backup_partition.marker", fg = "darkgray" },
  { url = "*{hiberfil,pagefile,swapfile}.sys", fg = "darkgray" },
  { url = "*ntuser*", fg = "darkgray" },
  { url = "*desktop.ini", fg = "darkgray" },

  { url = "*{$recycle.bin,system volume information}/", fg = "darkgray" },

  # hidden

  { url = "*", is = "hidden", fg = "darkgray" },
  { url = "*/", is = "hidden", fg = "darkgray" },

  # links

  { url = "*", is = "link", fg = "blue" },
  { url = "*/", is = "link", fg = "blue" },

  { url = "*", is = "orphan", fg = "red" },
  { url = "*/", is = "orphan", fg = "red" },

  # defaults

  { url = "*", fg = "reset" },
  { url = "*/", fg = "cyan" },
]

[icon]

dirs = [
  # no dir_colors from here

  { name = "code", text = "󱃪" },
  { name = "greg", text = "󰉌" },
  { name = "home", text = "󱂵" },
  { name = "users", text = "󱂵" },

  { name = "desktop", text = "" },
  { name = "downloads", text = "󰉍" },
  { name = "music", text = "󱍙" },
  { name = "pictures", text = "󰉏" },

  { name = ".cache", text = "󱐋" },
  { name = ".config", text = "" },
  { name = ".local", text = "󰆼" },

  { name = ".cert", text = "󱆈" },
  { name = ".pki", text = "󰍁" },
  { name = ".ssh", text = "" },

  { name = ".android", text = "" },
  { name = ".angular", text = "󰚲" },
  { name = ".ansible", text = "󱂚" },
  { name = ".azure-pipelines", text = "󰿕" },
  { name = ".devcontainer", text = "" },
  { name = ".dotnet", text = "" },
  { name = ".gemini", text = "" },
  { name = ".git", text = "" },
  { name = ".github", text = "󰊤" },
  { name = ".husky", text = "󰛢" },
  { name = ".idea", text = "" },
  { name = ".java", text = "" },
  { name = ".jupyter", text = "" },
  { name = ".m2", text = "" },
  { name = ".settings", text = "" },
  { name = ".swt", text = "" },
  { name = ".venv", text = "" },
  { name = ".vscode", text = "󰨞" },
  { name = ".yarn", text = "" },

  { name = "__pycache__", text = "" },
  { name = "dist", text = "" },
  { name = "node_modules", text = "󰎙" },

  { name = ".obsidian", text = "" },
  { name = ".steam", text = "󰓓" },
]

files = [
  { name = ".classpath", text = "" },
  { name = ".factorypath", text = "" },
  { name = ".project", text = "" },

  { name = ".dockerignore", text = "" },

  { name = ".editorconfig", text = "" },

  { name = ".env", text = "" },

  { name = ".lock", text = "󰤱" },

  { name = ".eslintignore", text = "" },
  { name = ".eslintrc", text = "" },
  { name = ".eslintrc.js", text = "" },
  { name = ".eslintrc.json", text = "" },
  { name = ".npmrc", text = "" },
  { name = ".nvmrc", text = "" },
  { name = ".yarnrc", text = "" },

  { name = ".git", text = "" },
  { name = ".gitattributes", text = "" },
  { name = ".gitignore", text = "" },
  { name = ".gitkeep", text = "" },
  { name = ".gitmodules", text = "" },

  { name = ".luacheckrc", text = "" },
  { name = ".luarc.json", text = "" },
  { name = ".stylua.toml", text = "" },

  { name = ".prettierignore", text = "" },
  { name = ".prettierrc", text = "" },

  { name = ".pylintrc", text = "" },

  { name = ".taplo.toml", text = "" },

  { name = ".vscodeignore", text = "󰨞" },

  # no dir_colors from here

  # { name = ".zprofile", text = "" },
  { name = ".zshenv", text = "" },
  { name = ".zshrc", text = "" },

  { name = "config", text = "" },

  { name = "credentials", text = "󱕴" },

  { name = "dir_colors,icons", text = "󰏘" },
  { name = "icons", text = "󰏘" },

  { name = "history", text = "" },
  { name = "history.txt", text = "" },

  { name = "lfrc", text = "" },
  { name = "npmrc", text = "" },
  { name = "ripgreprc", text = "" },

  { name = "LICENSE", text = "󰿃" },

  { name = "Dockerfile", text = "󰡨" },

  { name = "requirements.txt", text = "" },

  { name = "eslint.config.mjs", text = "" },

  { name = "go.mod", text = "" },
  { name = "go.sum", text = "" },

  { name = "pom.xml", text = "" },
]

exts = [
  { name = "AppImage", text = "󰘔" },
  { name = "flatpak", text = "󰘔" },

  { name = "nu", text = "" },
  { name = "sh", text = "" },
  { name = "zsh", text = "" },

  { name = "bat", text = "󰑷" },
  { name = "cmd", text = "󰑷" },
  { name = "exe", text = "" },
  { name = "ps1", text = "" },

  { name = "deb", text = "󰣚" },
  { name = "rpm", text = "󱄛" },

  { name = "7z", text = "" },
  { name = "gz", text = "" },
  { name = "rar", text = "" },
  { name = "tar", text = "" },
  { name = "zip", text = "" },

  { name = "cow", text = "󰋊" },
  { name = "fsa", text = "󰋊" },
  { name = "mrimg", text = "󰋊" },
  { name = "mrimgx", text = "󰋊" },
  { name = "wim", text = "󰋊" },

  { name = "iso", text = "󰗮" },

  { name = "ico", text = "" },
  { name = "jpeg", text = "" },
  { name = "jpg", text = "" },
  { name = "png", text = "" },
  { name = "svg", text = "󰕙" },

  { name = "flac", text = "󰝚" },
  { name = "m4a", text = "󰝚" },

  { name = "mkv", text = "󰷝" },
  { name = "mp4", text = "󰷝" },
  { name = "webm", text = "󰷝" },

  { name = "env", text = "" },

  { name = "lock", text = "󰤱" },

  { name = "backup", text = "󰘓" },
  { name = "bak", text = "󰘓" },
  { name = "log", text = "󰘓" },
  { name = "off", text = "󰘓" },
  { name = "old", text = "󰘓" },
  { name = "orig", text = "󰘓" },
  { name = "original", text = "󰘓" },
  { name = "part", text = "󰘓" },
  { name = "swp", text = "󰘓" },

  # no dir_colors from here

  { name = "icm", text = "󰏘" },
  { name = "otf", text = "" },
  { name = "ttf", text = "" },

  { name = "kdbx", text = "󰌾" },
  { name = "key", text = "" },

  { name = "gpg", text = "󰦝" },
  { name = "kbx", text = "󰯄" },

  { name = "pem", text = "" },
  { name = "pub", text = "󰷖" },

  { name = "cfg", text = "" },
  { name = "conf", text = "" },
  { name = "config", text = "" },
  { name = "rules", text = "" },
  { name = "service", text = "" },
  { name = "timer", text = "" },

  { name = "ini", text = "" },
  { name = "kdl", text = "" },

  { name = "json", text = "" },
  { name = "jsonc", text = "" },
  { name = "tmTheme", text = "󰗀" },
  { name = "xml", text = "󰗀" },
  { name = "toml", text = "" },
  { name = "yaml", text = "" },
  { name = "yml", text = "" },

  { name = "ahk", text = "󰑷" },
  { name = "vbs", text = "󰑷" },
  { name = "reg", text = "" },

  { name = "sql", text = "󰆼" },

  { name = "Dockerfile", text = "󰡨" },

  { name = "cs", text = "󰌛" },
  { name = "csproj", text = "󰗀" },
  { name = "sln", text = "󰗀" },

  { name = "go", text = "" },

  { name = "js", text = "" },
  { name = "mjs", text = "" },
  { name = "ts", text = "" },

  { name = "lua", text = "" },

  { name = "py", text = "" },

  { name = "rb", text = "" },

  { name = "rs", text = "" },

  { name = "java", text = "" },
  { name = "properties", text = "" },

  { name = "css", text = "" },
  { name = "html", text = "" },
  { name = "scss", text = "" },

  { name = "po", text = "" },
  { name = "pot", text = "" },

  { name = "md", text = "" },
  { name = "txt", text = "" },

  { name = "epub", text = "" },
  { name = "pdf", text = "" },

  { name = "csv", text = "" },
  { name = "xlsx", text = "" },
  { name = "docx", text = "" },

  { name = "qmd", text = "󰐗" },

  { name = "aux", text = "" },
  { name = "tex", text = "" },
]

conds = [
  { if = "hidden & dir", text = "󰷏" },
  { if = "hidden & !dir", text = "󰘓" },

  { if = "orphan", text = "󰌸" },
  { if = "link", text = "󰌷" },

  { if = "dir", text = "󰝰" },
  { if = "exec", text = "" },
  { if = "!dir", text = "󰈤" },
]
