"$schema" = "https://yazi-rs.github.io/schemas/theme.json"

[flavor]

use = ""

[manager]

cwd = { fg = "cyan" }

hovered = { reversed = true }
preview_hovered = {}

find_keyword = { fg = "yellow", bold = true }
find_position = { fg = "yellow", reversed = true }

marker_copied = { fg = "yellow", bg = "reset" }
marker_cut = { fg = "red", bg = "reset" }
marker_marked = { fg = "lightmagenta", bg = "reset" }
marker_selected = { fg = "magenta", bg = "reset" }

tab_active = { fg = "gray" }
tab_inactive = { fg = "darkgray" }
tab_width = 32

count_copied = { fg = "black", bg = "yellow" }
count_cut = { fg = "black", bg = "red" }
count_selected = { fg = "black", bg = "magenta" }

border_symbol = " "
border_style = { fg = "black" }

[status]

separator_open = ""
separator_close = ""
separator_style = { fg = "gray", bg = "gray" }

mode_normal = { fg = "black", bg = "gray" }
mode_select = { fg = "black", bg = "lightmagenta" }
mode_unset = { fg = "black", bg = "red" }

progress_label = { reverse = true }
progress_normal = { fg = "blue", bg = "reset" }
progress_error = { fg = "red", bg = "reset" }

permissions_t = { fg = "gray", bg = "reset" }
permissions_r = { fg = "gray", bg = "reset" }
permissions_w = { fg = "gray", bg = "reset" }
permissions_x = { fg = "gray", bg = "reset" }
permissions_s = { fg = "darkgray", bg = "reset" }

[select]

border = { fg = "darkgray" }
active = { fg = "reset" }
inactive = { fg = "gray" }

[input]

border = { fg = "darkgray" }
title = { fg = "darkgray" }
value = { fg = "reset" }
selected = { bg = "darkgray" }

[completion]

border = { fg = "darkgray" }
active = { fg = "reset" }
inactive = { fg = "gray" }

icon_file = "󰈤"
icon_folder = "󰝰"
icon_command = ""

[tasks]

border = { fg = "darkgray" }
title = { fg = "darkgray" }
hovered = { fg = "reset" }

[which]

cols = 2
mask = { bg = "reset" }
cand = { fg = "magenta" }
rest = { fg = "darkgray" }
desc = { fg = "gray" }
separator = " "

[help]

on = { fg = "magenta", bg = "reset" }
run = { fg = "darkgray" }
desc = { fg = "gray" }
hovered = { bold = true }
footer = { fg = "gray", bg = "reset" }

[notify]

title_info = { fg = "green" }
title_warn = { fg = "yellow" }
title_error = { fg = "red" }

icon_info = ""
icon_warn = ""
icon_error = ""

[filetype]

rules = [
  { name = "*", is = "exec", fg = "green" },

  { name = "*.AppImage", fg = "green" },

  { name = "*.{bat,cmd,exe,ps1}", fg = "green" },

  { name = "*.{7z,gz,rar,tar,zip}", fg = "yellow" },

  { name = "*.{cow,fsa,iso,mrimg,wim}", fg = "magenta" },

  { mime = "{audio,image,video}/*", fg = "magenta" },

  { name = "*.dockerignore", fg = "gray" },
  { name = "*.editorconfig", fg = "gray" },
  { name = "*.{env,eslintrc,eslintrc.js,eslintrc.json,npmrc,nvmrc,yarnrc}", fg = "gray" },
  { name = "*.{git,gitattributes,gitignore,gitkeep,gitmodules}", fg = "gray" },
  { name = "*.lock", fg = "gray" },
  { name = "*.{luacheckrc,luarc.json,stylua.toml}", fg = "gray" },
  { name = "*.{prettierignore,prettierrc}", fg = "gray" },
  { name = "*.pylintrc", fg = "gray" },
  { name = "*.taplo.toml", fg = "gray" },

  { name = "*.{backup,bak,log,off,old,orig,original,part,swp,tmp}", fg = "darkgray" },

  { name = "*.{cache,config,local}/", fg = "gray" },

  { name = "*.{cert,pki,ssh}/", fg = "gray" },

  { name = "*.{azure-pipelines,git,github,husky,vscode}/", fg = "gray" },

  { name = "*node_modules/", fg = "gray" },

  { name = "*.steam/", fg = "gray" },

  # windows

  { name = "*$winre_backup_partition.marker", fg = "darkgray" },
  { name = "*{hiberfil,pagefile,swapfile}.sys", fg = "darkgray" },
  { name = "*ntuser*", fg = "darkgray" },
  { name = "*desktop.ini", fg = "darkgray" },

  { name = "*{$recycle.bin,system volume information}/", fg = "darkgray" },

  # hidden

  { name = "**/.?*", fg = "darkgray" },
  { name = "**/.*/", fg = "darkgray" },

  # links

  { name = "*", is = "link", fg = "blue" },
  { name = "*/", is = "link", fg = "blue" },

  { name = "*", is = "orphan", fg = "red" },
  { name = "*/", is = "orphan", fg = "red" },

  # defaults

  { name = "*", fg = "reset" },
  { name = "*/", fg = "cyan" },
]

[icon]

dirs = [
  # no dir_colors from here

  { name = ".cache", text = "󱐋" },
  { name = ".config", text = "" },
  { name = ".local", text = "󰆼" },

  { name = ".cert", text = "󰍁" },
  { name = ".pki", text = "󰍁" },
  { name = ".ssh", text = "󰍁" },

  { name = ".azure-pipelines", text = "󰿕" },
  { name = ".git", text = "" },
  { name = ".github", text = "󰊤" },
  { name = ".husky", text = "󰛢" },
  { name = ".vscode", text = "󰨞" },

  { name = "node_modules", text = "󰎙" },

  { name = ".steam", text = "󰓓" },

  { name = ".git", text = "" },

  { name = "greg", text = "󱂵" },

  { name = "Desktop", text = "" },
  { name = "Documents", text = "󱧶" },
  { name = "Downloads", text = "󰉍" },
  { name = "Music", text = "󱍙" },
  { name = "Pictures", text = "󰉏" },
  { name = "Videos", text = "󱧺" },

  # windows

  { name = "$recycle.bin", text = "󰷏" },
  { name = "system volume information", text = "󰷏" },
]

files = [
  { name = ".dockerignore", text = "" },

  { name = ".editorconfig", text = "" },

  { name = ".env", text = "" },

  { name = ".eslintrc", text = "" },
  { name = ".eslintrc.js", text = "" },
  { name = ".eslintrc.json", text = "" },
  { name = ".npmrc", text = "" },
  { name = ".nvmrc", text = "" },
  { name = ".yarnrc", text = "" },

  { name = ".git", text = "" },
  { name = ".gitattributes", text = "" },
  { name = ".gitignore", text = "" },
  { name = ".gitkeep", text = "" },
  { name = ".gitmodules", text = "" },

  { name = ".luacheckrc", text = "" },
  { name = ".luarc.json", text = "" },
  { name = ".stylua.toml", text = "" },

  { name = ".prettierignore", text = "" },
  { name = ".prettierrc", text = "" },

  { name = ".pylintrc", text = "" },

  { name = ".taplo.toml", text = "" },

  # no dir_colors from here

  { name = "credentials", text = "󱕴" },

  { name = ".zprofile", text = "" },
  { name = ".zshenv", text = "" },
  { name = ".zshrc", text = "" },

  { name = "config", text = "" },

  { name = "dir_colors,icons", text = "󰏘" },
  { name = "icons", text = "󰏘" },

  { name = "history", text = "" },

  { name = "lfrc", text = "" },
  { name = "npmrc", text = "" },
  { name = "ripgreprc", text = "" },

  { name = "LICENSE", text = "󰿃" },

  { name = "Dockerfile", text = "󰡨" },

  { name = "go.mod", text = "" },
  { name = "go.sum", text = "" },
]

exts = [
  { name = "AppImage", text = "󰘔" },

  { name = "nu", text = "" },
  { name = "sh", text = "" },
  { name = "zsh", text = "" },

  { name = "bat", text = "󰑷" },
  { name = "cmd", text = "󰑷" },
  { name = "exe", text = "" },
  { name = "ps1", text = "" },

  { name = "7z", text = "" },
  { name = "gz", text = "" },
  { name = "rar", text = "" },
  { name = "tar", text = "" },
  { name = "zip", text = "" },

  { name = "cow", text = "󰋊" },
  { name = "fsa", text = "󰋊" },
  { name = "mrimg", text = "󰋊" },
  { name = "wim", text = "󰋊" },

  { name = "iso", text = "󰗮" },

  { name = "ico", text = "" },
  { name = "jpeg", text = "" },
  { name = "jpg", text = "" },
  { name = "png", text = "" },
  { name = "svg", text = "" },

  { name = "mp3", text = "󰝚" },
  { name = "ogg", text = "󰝚" },
  { name = "opus", text = "󰝚" },

  { name = "mkv", text = "󰷝" },
  { name = "mp4", text = "󰷝" },
  { name = "webm", text = "󰷝" },

  { name = "env", text = "" },

  { name = "lock", text = "󰤱" },

  { name = "backup", text = "󰘓" },
  { name = "bak", text = "󰘓" },
  { name = "log", text = "󰘓" },
  { name = "off", text = "󰘓" },
  { name = "old", text = "󰘓" },
  { name = "orig", text = "󰘓" },
  { name = "original", text = "󰘓" },
  { name = "part", text = "󰘓" },
  { name = "swp", text = "󰘓" },

  # no dir_colors from here

  { name = "icm", text = "󰏘" },
  { name = "otf", text = "" },
  { name = "ttf", text = "" },

  { name = "kdbx", text = "󰌾" },
  { name = "key", text = "" },

  { name = "gpg", text = "󰦝" },
  { name = "kbx", text = "󰯄" },

  { name = "pem", text = "" },
  { name = "pub", text = "󰷖" },

  { name = "conf", text = "" },
  { name = "rules", text = "" },
  { name = "service", text = "" },
  { name = "timer", text = "" },

  { name = "ini", text = "" },
  { name = "kdl", text = "" },

  { name = "json", text = "" },
  { name = "jsonc", text = "" },
  { name = "tmTheme", text = "󰗀" },
  { name = "xml", text = "󰗀" },
  { name = "toml", text = "" },
  { name = "yaml", text = "" },
  { name = "yml", text = "" },

  { name = "ahk", text = "󰑷" },
  { name = "vbs", text = "󰑷" },
  { name = "reg", text = "" },

  { name = "Dockerfile", text = "󰡨" },

  { name = "cs", text = "󰌛" },
  { name = "csproj", text = "󰗀" },
  { name = "sln", text = "󰗀" },

  { name = "go", text = "" },

  { name = "js", text = "" },
  { name = "ts", text = "" },

  { name = "lua", text = "" },

  { name = "py", text = "" },

  { name = "rb", text = "" },

  { name = "rs", text = "" },

  { name = "css", text = "" },
  { name = "html", text = "" },
  { name = "scss", text = "" },

  { name = "po", text = "" },

  { name = "md", text = "" },
  { name = "txt", text = "" },

  { name = "epub", text = "" },
  { name = "pdf", text = "" },

  { name = "csv", text = "" },
  { name = "xlsx", text = "" },
  { name = "docx", text = "" },
]

conds = [
  { if = "hidden & dir", text = "󰷏" },
  { if = "hidden & !dir", text = "󰘓" },

  { if = "orphan", text = "󰌸" },
  { if = "link", text = "󰌷" },

  { if = "dir", text = "󰝰" },
  { if = "exec", text = "" },
  { if = "!dir", text = "󰈤" },
]

rules = [
  # no yazi colors from here

  # windows

  { name = "*$winre_backup_partition.marker", text = "󰘓" },
  { name = "*{hiberfil,pagefile,swapfile}.sys", text = "󰘓" },
  { name = "*ntuser*", text = "󰘓" },
]
